export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SWITCH_THEME = 'SWITCH_THEME'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const GET_USER_NAME = 'GET_USER_NAME'
export const SWITCH_TAB = 'SWITCH_TAB'
export const NAME_TAB = 'NAME_TAB'
export const SLIDE_SHOW = 'SLIDE_SHOW'